// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "net/http"

type CVJob struct {
	JobID   int      `json:"jobId"`
	Bullets []string `json:"bullets"`
}

type CVEducation struct {
	EducationID int      `json:"educationId"`
	Bullets     []string `json:"bullets"`
}

type CVSkillCategory struct {
	SkillCategoryID int      `json:"skillCategoryId"`
	Bullets         []string `json:"bullets"`
}

type CV struct {
	ID      int    `json:"id"`
	Name    string `json:"name"`
	Summary string `json:"summary"`

	Jobs       []CVJob       `json:"jobs"`
	Educations []CVEducation `json:"educations"`

	Skills []CVSkillCategory `json:"skills"`
}

func cv() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav><a href=\"/cvs\">Back</a> <a href=\"/\">Home</a></nav><main><h1><span>CV</span></h1></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func handleCV(w http.ResponseWriter, r *http.Request) {
	page("CV", cv()).Render(r.Context(), w)
}

func init() {
	http.HandleFunc("GET /cv", handleCV)
}

var _ = templruntime.GeneratedTemplate
